---
- name: Set and lock GNOME wallpaper system-wide (Enterprise-Safe, improved)
  hosts: all
  become: yes
  become_user: root

  vars:
    # Source on the Ansible control node (relative or absolute path)
    wallpaper_source: "wallpaper.jpg"
    wallpaper_dest: "/usr/share/backgrounds/custom_wallpaper.jpg"
    picture_options: "centered"   # you can change to 'zoom', 'scaled', etc.

    dconf_dir: "/etc/dconf/db/local.d"
    dconf_file: "00-wallpaper"
    dconf_lock_dir: "/etc/dconf/db/local.d/locks"

  tags: [wallpaper, dconf]

  tasks:
    # -------------------------
    # 1. Ensure required directories exist
    # -------------------------
    - name: Ensure dconf directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ dconf_dir }}"
        - "{{ dconf_lock_dir }}"
      tags: [dirs]

    # -------------------------
    # 2. Copy wallpaper to system directory (backup enabled)
    # -------------------------
    - name: Copy wallpaper to system directory
      ansible.builtin.copy:
        src: "{{ wallpaper_source }}"
        dest: "{{ wallpaper_dest }}"
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: Update dconf database
      tags: [copy]

    # -------------------------
    # 3. Define system-wide wallpaper defaults
    # -------------------------
    - name: Create GNOME system-wide wallpaper config
      ansible.builtin.copy:
        dest: "{{ dconf_dir }}/{{ dconf_file }}"
        content: |
          [org/gnome/desktop/background]
          picture-uri='file://{{ wallpaper_dest }}'
          picture-uri-dark='file://{{ wallpaper_dest }}'
          picture-options='{{ picture_options }}'
        owner: root
        group: root
        mode: '0644'
      notify: Update dconf database
      tags: [dconf]

    # -------------------------
    # 4. Lock wallpaper settings so users cannot change
    # -------------------------
    - name: Create GNOME wallpaper lock file
      ansible.builtin.copy:
        dest: "{{ dconf_lock_dir }}/{{ dconf_file }}"
        content: |
          /org/gnome/desktop/background/picture-uri
          /org/gnome/desktop/background/picture-uri-dark
        owner: root
        group: root
        mode: '0444'
      notify: Update dconf database
      tags: [locks]

    # -------------------------
    # 5. Final confirmation message
    # -------------------------
    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          Wallpaper has been set to {{ wallpaper_dest }} and locked system-wide.
          If users are currently logged in, they will see the change at next GNOME login.
      tags: [info]

  handlers:
    - name: Update dconf database
      ansible.builtin.command: dconf update
      args:
        warn: false
      listen: "Update dconf database"
      become: yes
      become_user: root

# End of playbook
