---
# ==========================================================
# AWX Sysinfo Collector + Email (runs as SSH user)
# ==========================================================

- name: Collect detailed system info from all hosts
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    ####################################################################
    # --- REQUIRED TOOLS ----------------------------------------------
    ####################################################################
    - name: Ensure required packages are installed (robust and safe)
      block:
        - name: Check if required binaries already exist
          stat:
            path: "{{ item }}"
          register: pkg_binaries
          loop:
            - /usr/sbin/dmidecode
            - /usr/bin/lsblk
            - /usr/bin/lsb_release
          changed_when: false

        - name: Install missing tools
          apt:
            name:
              - dmidecode
              - util-linux
              - lsb-release
            state: present
            update_cache: yes
          environment:
            DEBIAN_FRONTEND: noninteractive
          when: >
            not (pkg_binaries.results | selectattr('stat.exists','equalto',true) | list | length == 3)
      rescue:
        - debug:
            msg: "⚠️ Package install failed; continuing with available tools."

    ####################################################################
    # --- CPU, RAM, and Storage Collection -----------------------------
    ####################################################################
    - name: Get CPU model
      shell: "lscpu | awk -F: '/Model name/ {print $2}' | sed 's/^ *//'"
      register: cpu_model
      changed_when: false

    - name: Get RAM slot usage and memory type
      shell: |
        total_slots=$(dmidecode -t memory | grep -E '^[[:space:]]*Memory Device' | wc -l)
        used_slots=$(dmidecode -t memory | grep -A5 'Memory Device' | grep -E 'Size: [1-9]' | wc -l)
        mem_type=$(dmidecode -t memory | awk -F: '/^[[:space:]]*Type:/{gsub(/^[ \t]+/, "", $2); if($2!="Unknown" && $2!="") {print $2; exit}}')
        [ -z "$mem_type" ] && mem_type="Unknown"
        echo "$used_slots/$total_slots,$mem_type"
      register: ram_info
      changed_when: false
      args:
        executable: /bin/bash

    - name: Get storage devices and classify
      shell: |
        total=0
        out=""
        while read -r name size rota type; do
          if [ "$type" != "disk" ]; then continue; fi
          gb=$(awk "BEGIN {printf \"%.2f\", $size/1024/1024/1024}")
          if [ "$rota" = "0" ]; then kind="SSD"; else kind="HDD"; fi
          out="$out $name:${kind}(${gb}GB)"
          total=$(awk "BEGIN {printf \"%.2f\", $total + $gb}")
        done < <(lsblk -b -d -o NAME,SIZE,ROTA,TYPE | tail -n +2)
        echo "$total,$out"
      register: disk_info
      changed_when: false
      args:
        executable: /bin/bash

    - name: Store system info
      set_fact:
        collected_sysinfo:
          hostname: "{{ ansible_hostname }}"
          cpu: "{{ cpu_model.stdout | default('N/A') }}"
          ram_mb: "{{ ansible_memtotal_mb }}"
          ram_slots: "{{ (ram_info.stdout.split(',')[0]) | default('N/A') }}"
          ram_type: "{{ (ram_info.stdout.split(',')[1]) | default('Unknown') }}"
          storage_gb: "{{ (disk_info.stdout.split(',')[0]) | default('0') }}"
          drives: "{{ (disk_info.stdout.split(',', 2)[1]) | default('N/A') }}"

    - name: Display system summary
      debug:
        msg: |
          🖥️ Hostname: {{ collected_sysinfo.hostname }}
          🧠 CPU: {{ collected_sysinfo.cpu }}
          💾 RAM: {{ collected_sysinfo.ram_mb }} MB
          🔢 Slots/Type: {{ collected_sysinfo.ram_slots }} ({{ collected_sysinfo.ram_type }})
          📦 Storage: {{ collected_sysinfo.storage_gb }} GB
          💽 Drives: {{ collected_sysinfo.drives }}

# ==========================================================
# MODULE 2 - Aggregate + Send Mail
# ==========================================================
- name: Aggregate reports and email from trusted host (as SSH user)
  hosts: 192.168.2.129
  gather_facts: no
  become: false
  run_once: true

  vars:
    report_dir: "~/hosts-info-ansible"
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    csv_file: "{{ report_dir }}/sysinfo_report_{{ timestamp }}.csv"
    json_file: "{{ report_dir }}/sysinfo_report_{{ timestamp }}.json"
    smtp_host: "smtpout.secureserver.net"
    smtp_port: 587
    mail_from: "{{ smtp_user }}"
    mail_to: "{{ smtp_user }}"        # same email from AWX credential
    subject: "AWX Sysinfo Report - {{ timestamp }}"

  tasks:
    - name: Ensure report directory exists
      file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'

    - name: Build aggregated data
      set_fact:
        data_list: "{{ hostvars | dict2items | map(attribute='value.collected_sysinfo') | select('defined') | list }}"

    - name: Write JSON report on trusted host
      copy:
        dest: "{{ json_file }}"
        content: "{{ data_list | to_nice_json }}"
        mode: '0644'

    - name: Write CSV report on trusted host (fix 2/4 → 2 of 4)
      copy:
        dest: "{{ csv_file }}"
        content: |
          "Hostname","CPU","RAM_MB","RAM_Slots","RAM_Type","Storage_GB","Drives"
          {% for i in data_list %}
          "{{ i.hostname }}","{{ i.cpu }}","{{ i.ram_mb }}","{{ i.ram_slots | regex_replace('([0-9]+)/([0-9]+)', '\\1 of \\2') }}","{{ i.ram_type }}","{{ i.storage_gb }}","{{ i.drives }}"
          {% endfor %}
        mode: '0644'

    - name: Confirm files exist on host
      stat:
        path: "{{ item }}"
      loop:
        - "{{ csv_file }}"
        - "{{ json_file }}"
      register: files

    - name: Display report file locations
      debug:
        msg: |
          ✅ Reports generated on {{ inventory_hostname }}:
          CSV: {{ csv_file }}
          JSON: {{ json_file }}

    - name: Send email with CSV + JSON attachments
      shell: |
        python3 - <<'PY'
        import smtplib, ssl, os
        from email.mime.text import MIMEText
        from email.mime.multipart import MIMEMultipart
        from email.mime.base import MIMEBase
        from email import encoders

        sender = "{{ smtp_user }}"
        password = "{{ smtp_pass }}"
        recipient = "{{ smtp_user }}"
        ts = "{{ timestamp }}"
        body = f"Attached are the latest system reports collected by AWX generated on {ts}.\n\nRegards,\nansible team"
        subject = "AWX Sysinfo Report - " + ts

        msg = MIMEMultipart()
        msg["From"] = sender
        msg["To"] = recipient
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        for p in ["{{ csv_file }}", "{{ json_file }}"]:
            if os.path.exists(os.path.expanduser(p)):
                with open(os.path.expanduser(p), "rb") as f:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header("Content-Disposition", f"attachment; filename={os.path.basename(p)}")
                    msg.attach(part)
            else:
                print(f"⚠️ File not found: {p}")

        ctx = ssl.create_default_context()
        with smtplib.SMTP("{{ smtp_host }}", {{ smtp_port }}) as server:
            server.starttls(context=ctx)
            server.login(sender, password)
            server.sendmail(sender, recipient, msg.as_string())
            print(f"📧 Email sent successfully to {recipient}")
        PY
      args:
        executable: /bin/bash

    - name: Final confirmation
      debug:
        msg: "✅ Email sent successfully to {{ smtp_user }} with attached reports: {{ csv_file }} and {{ json_file }}"

