---
- name: Collect and summarize system info using shell tools
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Ensure required tools exist
      apt:
        name:
          - dmidecode
          - lsb-release
          - util-linux
        state: present
        update_cache: yes
      changed_when: false

    ####################################################################
    # --- CPU INFO -----------------------------------------------------
    ####################################################################
    - name: Get CPU model
      shell: "lscpu | awk -F: '/Model name/ {print $2}' | sed 's/^ *//'"
      register: cpu_model
      changed_when: false

    ####################################################################
    # --- MEMORY INFO --------------------------------------------------
    ####################################################################
    - name: Get memory slot usage and type via dmidecode
      shell: |
        total_slots=$(dmidecode -t memory | grep -c '^Memory Device')
        used_slots=$(dmidecode -t memory | grep -A3 '^Memory Device' | grep -c 'Size: [1-9]')
        mem_type=$(dmidecode -t memory | awk -F: '/^\s*Type:/ {gsub(/^[ \t]+/, "", $2); if($2!="Unknown" && $2!="") {print $2; exit}}')
        if [ -z "$mem_type" ]; then mem_type="Unknown"; fi
        echo "$used_slots/$total_slots,$mem_type"
      register: ram_info
      changed_when: false

    ####################################################################
    # --- STORAGE INFO -------------------------------------------------
    ####################################################################
    - name: Collect block device info (filter real disks only)
      shell: |
        total=0
        out=""
        while read -r name size rota type; do
          if [ "$type" != "disk" ]; then continue; fi
          gb=$(awk "BEGIN {printf \"%.2f\", $size/1024/1024/1024}")
          if [ "$rota" = "0" ]; then kind="SSD"; else kind="HDD"; fi
          out="$out $name:${kind}(${gb}GB)"
          total=$(awk "BEGIN {printf \"%.2f\", $total + $gb}")
        done < <(lsblk -b -d -o NAME,SIZE,ROTA,TYPE | tail -n +2)
        echo "$total,$out"
      register: disk_info
      changed_when: false

    ####################################################################
    # --- SUMMARY OUTPUT -----------------------------------------------
    ####################################################################
    - name: Display concise system summary
      debug:
        msg: |
          ðŸ–¥ï¸ Hostname: {{ ansible_hostname }}
          ðŸ§  CPU: {{ cpu_model.stdout | default(ansible_processor[0] | default('N/A')) }}
          ðŸ’¾ Total RAM: {{ ansible_memtotal_mb }} MB
          ðŸ”¢ RAM Slots/Type: {{ ram_info.stdout.split(',')[0] | default('N/A') }} slots, Type {{ ram_info.stdout.split(',')[1] | default('Unknown') }}
          ðŸ“¦ Storage Total: {{ disk_info.stdout.split(',')[0] | default('0') }} GB
          ðŸ’½ Drives: {{ disk_info.stdout.split(',',2)[1] | default('N/A') }}

