---
- name: Set and lock system-wide wallpaper on Ubuntu
  hosts: ubuntu_nodes
  become: yes
  vars:
    wallpaper_source: "files/custom_wallpaper.jpg"
    wallpaper_dest: "/usr/share/backgrounds/custom_wallpaper.jpg"
    dconf_dir: "/etc/dconf/db/local.d"
    dconf_file: "00-wallpaper"
    dconf_lock_dir: "/etc/dconf/db/local.d/locks"

  tasks:
    # -------------------------
    # Ensure directories exist
    # -------------------------
    - name: "Ensure dconf directory exists"
      ansible.builtin.file:
        path: "{{ dconf_dir }}"
        state: directory
        mode: '0755'

    - name: "Debug: Dconf directory ensured"
      ansible.builtin.debug:
        msg: "Directory {{ dconf_dir }} exists or was created"

    - name: "Ensure dconf locks directory exists"
      ansible.builtin.file:
        path: "{{ dconf_lock_dir }}"
        state: directory
        mode: '0755'

    - name: "Debug: Dconf locks directory ensured"
      ansible.builtin.debug:
        msg: "Directory {{ dconf_lock_dir }} exists or was created"

    # -------------------------
    # Copy wallpaper
    # -------------------------
    - name: "Copy wallpaper to target machine"
      ansible.builtin.copy:
        src: "{{ wallpaper_source }}"
        dest: "{{ wallpaper_dest }}"
        mode: '0644'

    - name: "Debug: Wallpaper copy path"
      ansible.builtin.debug:
        msg: "Wallpaper copied to {{ wallpaper_dest }}"

    # -------------------------
    # Set wallpaper defaults
    # -------------------------
    - name: "Set system-wide wallpaper defaults"
      ansible.builtin.copy:
        dest: "{{ dconf_dir }}/{{ dconf_file }}"
        content: |
          [org/gnome/desktop/background]
          picture-uri='file://{{ wallpaper_dest }}'
          picture-uri-dark='file://{{ wallpaper_dest }}'
        mode: '0644'

    - name: "Debug: Dconf wallpaper defaults created"
      ansible.builtin.debug:
        msg: "Wallpaper defaults set at {{ dconf_dir }}/{{ dconf_file }}"

    # -------------------------
    # Lock wallpaper keys
    # -------------------------
    - name: "Lock wallpaper keys so users cannot change it"
      ansible.builtin.copy:
        dest: "{{ dconf_lock_dir }}/{{ dconf_file }}"
        content: |
          /org/gnome/desktop/background/picture-uri
          /org/gnome/desktop/background/picture-uri-dark
        mode: '0644'

    - name: "Debug: Wallpaper keys locked"
      ansible.builtin.debug:
        msg: "Wallpaper keys locked in {{ dconf_lock_dir }}/{{ dconf_file }}"

    # -------------------------
    # Apply changes
    # -------------------------
    - name: "Update dconf database"
      ansible.builtin.command: dconf update

    - name: "Debug: Dconf database updated"
      ansible.builtin.debug:
        msg: "Dconf database updated successfully"


